package com.chat.app.realtimechat.model;

import jakarta.persistence.*;
import lombok.Data; // Lombok is added as a dependency in pom.xml

@Entity // Marks this class as a JPA entity, mapping it to a database table
@Data // From Lombok: Automatically generates getters, setters, toString, equals, and hashCode methods
@Table(name = "app_user") // New: Specify a different table name to avoid SQL reserved keyword issues
public class User {
    @Id // Specifies that 'id' is the primary key of the entity
    @GeneratedValue(strategy= GenerationType.IDENTITY)  // Configures the primary key to be auto-generated by the database
    private Long id; // Use Long (wrapper class) for the primary key

    @Column(unique=true, nullable=false) // Ensures the username is unique across all users and cannot be null
    private String username; // The username for the chat application
}